import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
import { Toaster } from "~/components/ui/sonner";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/custom/app-sidebar";
import TopBar from "~/components/ui/topbar";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <SessionProvider>
        <body>
          <TRPCReactProvider>
            <TopBar />
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
          </TRPCReactProvider>
          <Toaster />
        </body>
      </SessionProvider>
    </html>
    // <html lang="en" className={`${geist.variable}`}>
    //   <SessionProvider>
    //   <body>
    //     <TRPCReactProvider>{children}</TRPCReactProvider>
    //     <Toaster />
    //   </body>
    //   </SessionProvider>
    // </html>
  );
}

{/* <html lang="en" className={`${geist.variable}`}>
      <SessionProvider>
        <body>
          <TRPCReactProvider>
            <SidebarProvider>
              <AppSidebar />
              <main>
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
          </TRPCReactProvider>
          <Toaster />
        </body>
      </SessionProvider>
    </html> */}